### ISSUE TITLE
[Windows] Microsoft Defender SmartScreen Blocks Masscode

### ISSUE THREAD

**Issue by GaryFurash** [antonreshetov/massCode#135] opened 2021-01-18 15:10 UTC
## Describe the bug

Downloading Masscode is blocked by Microsoft Defender

## To Reproduce

Windows 10, Download

**Example:**
massCodeSetup1.3. exe was blocked

**Comment by antonreshetov** [comment] 2021-02-17 07:45
Duplicate of #38

**Closed by antonreshetov** 2021-02-17 07:45 UTC
