### ISSUE TITLE
The application “massCode” can’t be opened.

### ISSUE THREAD

**Issue by danieltoro** [antonreshetov/massCode#24] opened 2020-01-20 22:57 UTC
I cannot open masscode on Mac.

I recently install Catalina but I cant open before install.

**Comment by blcarson** [comment] 2020-01-21 08:54
Try opening the application normally once. After you cancel the error, right click and then hit "Open" - this should bypass Catalina's wonky "security"

**Comment by antonreshetov** [comment] 2020-01-22 09:52
Duplicate of #21

**Closed by antonreshetov** 2020-01-22 09:52 UTC
Labels: duplicate
