### ISSUE TITLE
backup now button doesn't work

### ISSUE THREAD

**Issue by dcy10000** [antonreshetov/massCode#72] opened 2020-03-06 15:21 UTC
## Describe the bug

when I click the "backup now" button, nothing happened.
Is this backup function stable now?

**Comment by antonreshetov** [comment] 2020-03-12 04:27
I couldn't reproduce this bug.

**Comment by estarq** [comment] 2020-03-23 20:14
On Linux default directory for massCode's backups is ~/massCode/backups which simply doesn't exist.
When it does, everything seems to work just fine.

**Comment by dcy10000** [comment] 2020-03-24 05:25
> On Linux default directory for massCode's backups is ~/massCode/backups which simply doesn't exist.
> When it does, everything seems to work just fine.

thx. It works! 
But, the introduction I see is that "Backup will be created automatically when massCode is running.",
I haven't seen any automatic backups yet. 
How often does it trigger ？

**Comment by estarq** [comment] 2020-03-24 11:39
Take a look:
https://github.com/antonreshetov/massCode/blob/4a7bc7c6793d0f599741c80185ac52176bd21e89/src/renderer/datastore.js#L98-L120

**Comment by antonreshetov** [comment] 2020-04-04 06:46
Closed because it was fixed in #90

**Closed by antonreshetov** 2020-04-04 06:46 UTC
Labels: needs reproduce
