### ISSUE TITLE
All files was lost when select D:\ drive in Move storage feature

### ISSUE THREAD

**Issue by gioxoay** [antonreshetov/massCode#10] opened 2020-01-12 16:29 UTC
When click to Move storage button, I was select my D:\ drive and this app was delete everything in my drive. This is f**k app, make all my files lost.

**Comment by antonreshetov** [comment] 2020-01-12 17:29
First, I checked and I couldn't reproduce the problem. Second, the application is in unstable version, it can be understood by the version number and the message on the site - "Exclusively for introductory purposes. Please do not use as a primary tool until the stable build". Thirdly, it seems to me that this behavior is not acceptable at all. Good luck to you!

**Comment by btrsco** [comment] 2020-01-25 01:43
I installed and changed the default directory to my development folder assuming that it would just create its own folder, but it deleted the entire contents of that folder and replaced it with its db files. Not cool. I lost all my recent work. thankfully some are in GitHub repos, but not all and I can't seem to find them anywhere since they were deleted programmatically.

This happened in the macOS version of the app. Extremely pissed.

**Comment by dfanara** [comment] 2020-01-25 02:08
@antonreshetov I find your response to this issue to be incredibly lazy. Rather than understand the cause of the issue, you simply shrugged it off and decided it wasn't your problem. I found your problem in less than ten minutes. This should be a critical issue. Everyone attempting to see your software should be aware of this.

For the record, src/renderer/datastore.js, lines 43-51. If you look at your async move(to) function, you are replacing the entire directory with the previous directory. (Line 45). With the overwrite: true parameter, you are completely wiping out the original directory and replacing it with your previous directly, which includes snippets.db, tags.db, masscode.db.

**Comment by antonreshetov** [comment] 2020-01-25 02:51
My deepest apologies! c414e12f1e2a25ebdff7c31702a21ca0a21085eb should fix the problem. 

Please check latest build - https://github.com/antonreshetov/massCode/releases/tag/v1.0.0-aplha.4

I also want to remind you that I develop this in my spare time, which is not paid, so talking about the speed of response to certain bugs looks strange.

**Comment by antonreshetov** [comment] 2020-01-29 03:59
Closed because it was fixed in https://github.com/antonreshetov/massCode/commit/c414e12f1e2a25ebdff7c31702a21ca0a21085eb

**Closed by antonreshetov** 2020-01-29 03:59 UTC
Labels: bug, needs reproduce, win
